### ISSUE TITLE
DeprecationWarning: Attribute s is deprecated and will be removed in Python 3.14; use value instead

### ISSUE THREAD

**Issue by RomainBrault** [Erotemic/xdoctest#164]
```

DeprecationWarning: Attribute s is deprecated and will be removed in Python 3.14; use value instead
```
Raised on windows GitHub runner under Python 3.13 (via UV)

Spotted on main:

https://github.com/Erotemic/xdoctest/blob/f85735b6a17a7bd93f50b06b160488336d86485d/src/xdoctest/static_analysis.py#L421

**Comment by RomainBrault** [comment]
I don't know why this is only raised on windows runner (linux and osx are fine). Plus xdoctests seems to check whether Python >= 3.12

**Comment by Erotemic** [comment]
Very strange, that line of code should not be hit on 3.13. 

Am I doing something wrong here?

```
IS_PY_GE_312 = sys.version_info[0] >= 3 and sys.version_info[1] >= 12
```

Can you verify what the value of `sys.version_info` is in your environment?

**Comment by RomainBrault** [comment]
The problem only occurs when requiring xdoctests[all]

I think there is some problem when resolving dependencies on windows with Python 3.13 and uv fallback on an old version of xdoctests[all] to satisfy the constraints.

 * If I pin xdoctests[all] >=1.2.0 the dependency resolver just fails
 * If I remove all extras (e.g. xdoctests >= 1.20) everythings run fine (dependency resolver succeed and no deprecation warning emited)

So I think there is something "wrong" in https://github.com/Erotemic/xdoctest/blob/main/requirements/jupyter.txt

**Comment by Erotemic** [comment]
Ah, that must be the issue. Tricky.

FWIW, you probably shouldn't use `xdoctest[all]`, as it gives you everything that is needed for all CI tests, but at the same time, if it is introducing unsatisfiable dependencies it should be fixed.

If you want all features as a user you probably want  `uv pip install xdoctest[colors]`. Perhaps I need to rethink the "all" extras as it does look deceptively enticing from a the perspective of a user who wants full functionality of a package. Maybe making it "all-dev" would clear up some confusion? I'll need to think about it. The extras in this package are not very clear. 

My guess is that this might be caused by `debugpy`, because there does not appear to be a 3.13 wheel for it.

Other candidate problematic packages could be `ipython_genutils`, everything else looks like it is agnostic to Python version.

**Comment by RomainBrault** [comment]
Yes I was a bit lost because the only extra documented was color, and in the documentation "getting started: 0" give the install example with "all". I just install xdoctests[all] without trying to understand what's happening (Cargo cult programming).

I think some documentation on the extras would be nice!

**Comment by Erotemic** [comment]
Noted, I will add that. Thank you for the feedback. It really helps me understand where I can make impactful improvements.
