### ISSUE TITLE
Package xdoctest for conda-forge ?

### ISSUE THREAD

**Issue by Zeitsperre** [Erotemic/xdoctest#71]
Hi,

I just came across `xdoctest` via your PyCon presentation (great publicity) and it looks like it could be very useful in a few projects I'm associated with. I was wondering though if you had considered packaging it for [conda-forge](https://conda-forge.org/). The process isn't very difficult (I maintain a few packages listed through there) and I could contribute some help in setting it up if you were willing to maintain it.

Best,

**Comment by Erotemic** [comment]
Yes, I'm absolutely willing to maintain it and I'd be greatly appreciative of any help in setting it up. 

I use conda to install my default Python interpreter, but I almost always use pip to install and maintain packages in my environment (except for gdal because of its difficult-to-use C bindings). I see that a lot of packages are maintained on both pypi and conda-forge, so I think doing the same here is reasonable. I am curious though, what is the benefit of packaging a pure-python package on conda-forge when it is also on pypi? 

Regardless, if you make a PR that lays out the appropriate template, I'll get it merged, do anything I need to do on the account / authentication side, and maintain it as needed.

**Comment by Erotemic** [comment]
Closing because it looks like there already is one .
