### ISSUE TITLE
Can't seem to inject testdata to xdoctest namespace

### ISSUE THREAD

**Issue by Zeitsperre** [Erotemic/xdoctest#79]
Following the examples from doctest, I've been trying to set up the pytest fixtures for xdoctest via a `conftest.py` housed in a separate test folder. These fixtures point to a `testdata` folder and map out many of the example files, for example:

```
@pytest.fixture(autouse=True)
def add_example_file_paths(xdoctest_namespace):
    """Add these datasets in the doctests scope."""
    ns = xdoctest_namespace
    ns["path_to_pr_file"] = str(TD / "NRCANdaily" / "nrcan_canada_daily_pr_1990.nc")

    ns["path_to_tasmax_file"] = str(
        TD / "NRCANdaily" / "nrcan_canada_daily_tasmax_1990.nc"
    )
    ...
```

These files are found without issue for standard pytests found in the `tests` folder, but these files don't seem to exist in the namespace of the library modules themselves when `pytest --xdoctest my_module/` is run. The output I get suggests that these addresses aren't found:

```
* REASON: NameError
DOCTEST DEBUG INFO
  XDoc "/home/tjs/git/xclim/xclim/indices/_anuclim.py::temperature_seasonality:0", line 3 <- wrt doctest
  File "/home/tjs/git/xclim/xclim/indices/_anuclim.py", line 118, <- wrt source file
DOCTEST PART BREAKDOWN
Failed Part:
    1 >>> import xarray as xr
    2 >>> import xclim.indices as xci
    3 >>> t = xr.open_dataset(path_to_tasmax_file).tas
Remaining Parts:
    4 >>> tday_seasonality = xci.temperature_seasonality(t)  # doctest: +SKIP
    5 >>> t_weekly = xci.tg_mean(t, freq='7D')  # doctest: +SKIP
    6 >>> tweek_seasonality = xci.temperature_seasonality(t_weekly)  # doctest: +SKIP
DOCTEST TRACEBACK
Traceback (most recent call last):

  File "/home/tjs/miniconda3/envs/xclim38/lib/python3.8/site-packages/xdoctest/doctest_example.py", line 536, in run
    exec(code, test_globals)

  File "<doctest:/home/tjs/git/xclim/xclim/indices/_anuclim.py::temperature_seasonality:0>", line rel: 3, abs: 118, in <module>
    >>> t = xr.open_dataset(path_to_tasmax_file).tas

NameError: name 'path_to_tasmax_file' is not defined
```

Is there an option I'm forgetting or is there a different method for injecting the namespace of xdoctest with paths to testdata?

**Comment by Erotemic** [comment]
At this time I don't believe xdoctest supports fixtures like this. Xdoctest was written to mostly operate as a standalone program, and the pytest plugin is supposed to be a non-intrusive addon.  So, I don't think there is any easy way to inject variables into the namespace of an executing doctest.

There is a way to inject code into the beginning of every doctest via the `--global-exec="<arbitrary-code>"`.   Or `--xdoc-global-exec` when running via pytest. 

However, I would strongly recommend against using anything that "injects" code into a doctest. At that point a doctest fails to be runnable in a standalone manner and thus fails to be useful for other developers. It would be likely to cause confusion because there is some variable being used but no clear indication of where it comes from. 

Instead perhaps your package can have a module called "mymod.data" or something like that and when you need `path_to_tasmax_file` you write 


```python
>>> from mymod.data import grab_testdata
>>> path_to_tasmax_file = grab_testdata()
```

in which case you can do whatever global magic you want to influence the behavior of grab_testdata and it is clear to readers of the doctest where the magic test data is coming from. IMHO this would be much better practice. 

As an opinionated aside, I feel that pytest fixtures often make it more difficult to maintain a project, and I would not recommend using them in general, but especially not for doctests.

**Comment by Erotemic** [comment]
Marking this as closed. Reopen if you need to.
